inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

LineLength:
  Max: 130

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "app/assets"
    - "app/channels"
    - "app/jobs"
    - "bin/*"
    - "lib/*"
    - "log/*"
    - "public/*"
    - "storage/*"
    - "test/*"
    - "tmp/*"
    - "vendor/*"
    - "**/Gemfile"
    - .git/**/*"
    - "spec/**/*"
  NewCops: enable
  TargetRubyVersion: 2.7.5
