version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.5
    working_directory: ~/parents_app
    steps:
      - checkout:
          path: ~/parents_app
      - ruby/install-deps

  rspec:
    docker:
      - image: cimg/ruby:2.7.5
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: myapp_test
          MYSQL_USER: user
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/parents_app
    steps:
      - checkout:
          path: ~/parents_app
      - ruby/install-deps
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Rspec
          command: bundle exec rspec
      - run:
          name: yarn Install
          command: yarn install
      - run: bundle exec bin/webpack

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - rspec:
          requires:
            - build
